# Generated by Django 5.1.7 on 2025-04-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0002_feedbackquestion_feedbackresponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackquestion',
            name='response_type',
            field=models.CharField(choices=[('paragraph', 'Paragraph'), ('checkbox', 'Checkbox'), ('rating', 'Rating'), ('text', 'Text'), ('multiple_choice', 'Multiple Choice'), ('yes_no', 'Yes/No'), ('scale', 'Scale')], max_length=20),
        ),
    ]
