# Generated by Django 5.1.7 on 2025-05-09 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0003_alter_feedbackquestion_response_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
