# Generated by Django 5.1.7 on 2025-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0005_sessionstatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_name',
        ),
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
