# Generated by Django 5.1.7 on 2025-06-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0007_alter_participant_nic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='nic',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
